import { NativeOldschoolTranscriptControls } from "./NativeOldschoolTranscriptControls.jsx";
import { useRef, useState } from "react";
import { FileUp, Plus, Trash2, Upload } from "lucide-react";

import { StageGeometryControls } from "../../../components/builder-studio/StageGeometryControls.jsx";
import { StageSelectionFrame } from "../../../components/builder-studio/StageSelectionFrame.jsx";
import { StudioButton, StudioField } from "../../../components/builder-studio/StudioControls.jsx";
import { formatNativeListeningTime } from "../../../components/native-listening/nativeListeningRuntime.js";
import { nativeOldschoolListeningRegionStyle } from "../../../components/native-oldschool-listening/nativeOldschoolListeningRuntime.js";
import { NATIVE_OLDSCHOOL_LISTENING_LIMITS } from "../../../data/native-activities/nativeOldschoolListening.js";
import "./nativeOldschoolListeningAuthoring.css";

function TimingPlayer({ audioUrl, durationMs, playheadMs, onTime }) {
  const audioRef = useRef(null); const [playing, setPlaying] = useState(false);
  const update = () => { if (audioRef.current) onTime(Math.round(audioRef.current.currentTime * 1_000)); };
  return <section className="native-oldschool-timing-player" aria-label="Oldschool Listening timing player">
    <audio ref={audioRef} hidden src={audioUrl} preload="metadata" onTimeUpdate={update} onSeeked={update} onPlay={() => setPlaying(true)} onPause={() => { setPlaying(false); update(); }} onEnded={() => setPlaying(false)} />
    <button type="button" disabled={!audioUrl} onClick={() => audioRef.current?.paused ? audioRef.current.play().catch(() => {}) : audioRef.current?.pause()}>{playing ? "Pause" : "Play"}</button>
    <input type="range" min="0" max={Math.max(durationMs, 1)} step="100" value={Math.min(playheadMs, Math.max(durationMs, 1))} disabled={!audioUrl || !durationMs} onChange={(event) => { const value = Number(event.target.value); if (audioRef.current) audioRef.current.currentTime = value / 1_000; onTime(value); }} aria-label="Timing playhead" />
    <output>{formatNativeListeningTime(playheadMs)} / {formatNativeListeningTime(durationMs)}</output>
  </section>;
}

export function NativeOldschoolListeningTimelineAuthoring({ interaction, audioReference, pageReference, assetUrl, uploading, uploadAudio, uploadPage, importSrt, importJson, exportJson, cues, selectedCue, selectedCueId, setSelectedCueId, playheadMs, setPlayheadMs, addCue, removeCue, moveCue, mutatePublic, setCueTime }) {
  return <div className="native-oldschool-authoring-grid">
    <section className="studio-content-panel"><h3>Managed presentation assets</h3>
      <label className="studio-upload-action"><Upload aria-hidden="true" /><span><strong>{uploading === "audio" ? "Uploading…" : audioReference ? "Replace MP3" : "Upload MP3"}</strong><small>MP3 · maximum 50 MiB</small></span><input type="file" accept="audio/mpeg,.mp3" disabled={Boolean(uploading)} onChange={(event) => { uploadAudio(event.target.files?.[0]); event.target.value = ""; }} /></label>
      <label className="studio-upload-action"><Upload aria-hidden="true" /><span><strong>{uploading === "page" ? "Uploading…" : pageReference ? "Replace page image" : "Upload page image"}</strong><small>PNG, JPEG or WebP · intrinsic dimensions become the mapping coordinate system</small></span><input type="file" accept="image/png,image/jpeg,image/webp" disabled={Boolean(uploading)} onChange={(event) => { uploadPage(event.target.files?.[0]); event.target.value = ""; }} /></label>
      <StudioField label="Page image alt text"><textarea value={interaction.panels[1].altText} maxLength="2000" onChange={(event) => mutatePublic((next) => { next.parts[0].interaction.panels[1].altText = event.target.value; })} /></StudioField>
    </section>
    <section className="studio-content-panel"><header><h3>Audio timeline and cue text</h3><div className="studio-inline-actions"><label className="studio-upload-action"><FileUp aria-hidden="true" /><span><strong>Import SRT</strong><small>Strict validation; replacing existing mappings requires confirmation</small></span><input type="file" accept=".srt,application/x-subrip,text/plain" onChange={(event) => { importSrt(event.target.files?.[0]); event.target.value = ""; }} /></label><label className="studio-upload-action"><FileUp aria-hidden="true" /><span><strong>Import mapping JSON</strong><small>Strict canonical JSON · maximum 1 MiB</small></span><input type="file" accept="application/json,.json" onChange={(event) => { importJson(event.target.files?.[0]); event.target.value = ""; }} /></label><button type="button" onClick={exportJson}>Export mapping JSON</button></div></header>
      <TimingPlayer audioUrl={audioReference ? assetUrl(audioReference.assetId) : ""} durationMs={interaction.audioDurationMs} playheadMs={playheadMs} onTime={setPlayheadMs} />
      <div className="native-oldschool-cue-list">{cues.map((cue, index) => <button type="button" key={cue.id} aria-current={cue.id === selectedCueId ? "true" : undefined} onClick={() => setSelectedCueId(cue.id)}><strong>Cue {index + 1}</strong><span>{formatNativeListeningTime(cue.startMs)}–{formatNativeListeningTime(cue.endMs)}</span><small>{cue.highlightRegions.length ? `${cue.highlightRegions.length} mapped region${cue.highlightRegions.length === 1 ? "" : "s"}` : "Unmapped"}</small></button>)}</div>
      <StudioButton onClick={addCue} disabled={cues.length >= NATIVE_OLDSCHOOL_LISTENING_LIMITS.cues}><Plus /> Add Cue</StudioButton>
      {selectedCue ? <div className="studio-content-panel"><StudioField label="Cue text"><textarea value={selectedCue.text} maxLength="4000" onChange={(event) => mutatePublic((next) => { next.parts[0].interaction.cues.find((entry) => entry.id === selectedCue.id).text = event.target.value; })} /></StudioField><div className="studio-number-grid"><StudioField label="Start (MM:SS)"><input key={`start-${selectedCue.id}-${selectedCue.startMs}`} defaultValue={formatNativeListeningTime(selectedCue.startMs)} onBlur={(event) => setCueTime("startMs", event.target.value)} /></StudioField><StudioButton onClick={() => setCueTime("startMs", playheadMs)}>Set Start</StudioButton><StudioField label="End (MM:SS)"><input key={`end-${selectedCue.id}-${selectedCue.endMs}`} defaultValue={formatNativeListeningTime(selectedCue.endMs)} onBlur={(event) => setCueTime("endMs", event.target.value)} /></StudioField><StudioButton onClick={() => setCueTime("endMs", playheadMs)}>Set End</StudioButton></div><div className="studio-inline-actions"><button type="button" disabled={cues.indexOf(selectedCue) === 0} onClick={() => setSelectedCueId(cues[cues.indexOf(selectedCue) - 1]?.id)}>Previous</button><button type="button" disabled={cues.indexOf(selectedCue) === cues.length - 1} onClick={() => setSelectedCueId(cues[cues.indexOf(selectedCue) + 1]?.id)}>Next</button><button type="button" disabled={cues.indexOf(selectedCue) === 0} onClick={() => moveCue(-1)}>Move Up</button><button type="button" disabled={cues.indexOf(selectedCue) === cues.length - 1} onClick={() => moveCue(1)}>Move Down</button><button type="button" onClick={removeCue}>Delete Cue</button></div></div> : null}
    </section>
  </div>;
}

function sourcePoint(event, root, surface) {
  const bounds = root.getBoundingClientRect();
  return { x: Math.max(0, Math.min(surface.width, Math.round((event.clientX - bounds.left) / bounds.width * surface.width))), y: Math.max(0, Math.min(surface.height, Math.round((event.clientY - bounds.top) / bounds.height * surface.height))) };
}

export function NativeOldschoolListeningPageMappingAuthoring({ publicDocument, bookSlug, componentSlug, interaction, pageReference, assetUrl, selectedCue, selectedCueId, setSelectedCueId, selectedRegionId, setSelectedRegionId, mutatePublic, addRegion, updateRegion, removeRegion, clearCueMappings, clearMappings }) {
  const panel = interaction.panels[1]; const surface = { width: panel.sourceWidth, height: panel.sourceHeight };
  const rootRef = useRef(null); const startRef = useRef(null); const draftRef = useRef(null); const [draft, setDraft] = useState(null); const [drawMode, setDrawMode] = useState(false);
  const selectedRegion = selectedCue?.highlightRegions.find((region) => region.id === selectedRegionId) || null;
  const pointerDown = (event) => { if (!drawMode || !selectedCue || !rootRef.current || event.button !== 0) return; const point = sourcePoint(event, rootRef.current, surface); const next = { x: point.x, y: point.y, width: 1, height: 1 }; startRef.current = point; draftRef.current = next; setDraft(next); event.currentTarget.setPointerCapture(event.pointerId); };
  const pointerMove = (event) => { if (!startRef.current || !rootRef.current) return; const point = sourcePoint(event, rootRef.current, surface); const next = { x: Math.min(startRef.current.x, point.x), y: Math.min(startRef.current.y, point.y), width: Math.max(1, Math.abs(point.x - startRef.current.x)), height: Math.max(1, Math.abs(point.y - startRef.current.y)) }; draftRef.current = next; setDraft(next); };
  const pointerUp = () => { const completed = draftRef.current; if (completed && completed.width >= 8 && completed.height >= 8) addRegion(completed); startRef.current = null; draftRef.current = null; setDraft(null); setDrawMode(false); };
  return <div className="native-oldschool-mapping-workspace">
    <aside className="native-oldschool-mapping-cues"><h3>Cues</h3>{interaction.cues.map((cue, index) => <button type="button" key={cue.id} aria-current={cue.id === selectedCueId ? "true" : undefined} data-mapped={cue.highlightRegions.length > 0 || undefined} onClick={() => { setSelectedCueId(cue.id); setSelectedRegionId(cue.highlightRegions[0]?.id || null); }}><strong>Cue {index + 1}</strong><span>{cue.text}</span><small>{cue.highlightRegions.length ? `${cue.highlightRegions.length} region${cue.highlightRegions.length === 1 ? "" : "s"}` : "Unmapped"}</small></button>)}</aside>
    <section className="studio-content-panel"><header><div><h3>Page image mapping</h3><p>Draw one or more rectangles on the uploaded image. Geometry is stored in intrinsic source pixels.</p></div><div className="studio-inline-actions"><StudioButton onClick={() => setDrawMode((value) => !value)} disabled={!pageReference || !selectedCue || selectedCue.highlightRegions.length >= NATIVE_OLDSCHOOL_LISTENING_LIMITS.regionsPerCue}>{drawMode ? "Cancel drawing" : "Draw highlight region"}</StudioButton><StudioButton variant="danger-ghost" onClick={clearMappings} disabled={!interaction.cues.some((cue) => cue.highlightRegions.length || cue.scrollY !== null)}>Clear all mappings</StudioButton></div></header>
      <div className="native-oldschool-mapping-viewport"><div ref={rootRef} className="native-oldschool-mapping-canvas" data-studio-stage data-surface-width={surface.width} data-surface-height={surface.height} data-drawing={drawMode || undefined} style={{ aspectRatio: `${surface.width}/${surface.height}` }} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp}>
        {pageReference ? <img src={assetUrl(pageReference.assetId)} alt={panel.altText || "Oldschool Listening page awaiting alt text"} draggable="false" /> : <p>Upload a page image in Audio & Timeline before mapping.</p>}
        {interaction.cues.flatMap((cue) => cue.highlightRegions.map((region) => <button type="button" key={region.id} className="native-oldschool-mapping-region" data-active-cue={cue.id === selectedCueId || undefined} aria-label={`${cue.id === selectedCueId ? "Selected cue" : "Other cue"} highlight region`} aria-pressed={region.id === selectedRegionId} style={nativeOldschoolListeningRegionStyle(region, surface)} onClick={(event) => { event.stopPropagation(); setSelectedCueId(cue.id); setSelectedRegionId(region.id); }} />))}
        {draft ? <div className="native-oldschool-mapping-draft" style={nativeOldschoolListeningRegionStyle(draft, surface)} /> : null}
        {selectedRegion ? <StageSelectionFrame geometry={selectedRegion} stage={surface} label="Oldschool Listening highlight region" minWidth={8} minHeight={8} onChange={updateRegion} onClear={() => setSelectedRegionId(null)} onDelete={removeRegion} zIndex={20} /> : null}
      </div></div>
      <NativeOldschoolTranscriptControls {...{ publicDocument, bookSlug, componentSlug, assetUrl, selectedCue, selectedRegion, mutatePublic }} />
      {selectedCue ? <div className="native-oldschool-mapping-properties"><h4>Selected cue mappings</h4><div className="native-oldschool-region-chips">{selectedCue.highlightRegions.map((region, index) => <button key={region.id} type="button" aria-current={region.id === selectedRegionId ? "true" : undefined} onClick={() => setSelectedRegionId(region.id)}>Region {index + 1}</button>)}</div><StudioField label="Authored scroll target Y (source pixels)"><input type="number" min="0" max={surface.height} value={selectedCue.scrollY ?? ""} placeholder="Automatic from highlight union" onChange={(event) => mutatePublic((next) => { const cue = next.parts[0].interaction.cues.find((entry) => entry.id === selectedCue.id); cue.scrollY = event.target.value === "" ? null : Math.max(0, Math.min(surface.height, Math.round(Number(event.target.value)))); })} /></StudioField><StudioButton variant="danger-ghost" onClick={clearCueMappings} disabled={!selectedCue.highlightRegions.length && selectedCue.scrollY === null}>Clear selected cue mappings</StudioButton>{selectedRegion ? <><StageGeometryControls area={selectedRegion} stage={surface} label="Oldschool Listening highlight region" minWidth={8} minHeight={8} onChange={updateRegion} /><StudioButton variant="danger-ghost" onClick={removeRegion}><Trash2 /> Delete region</StudioButton></> : null}</div> : <p>Add or import a cue, then select it to map the page.</p>}
    </section>
  </div>;
}
