export function NativeMarkWordsMarkerControls({ label, marker, onChange, graphics, onUpload, outlineOnly = false }) {
  const change = (key, value) => onChange({ ...marker, [key]: value, ...(key === "kind" ? { graphicAssetSlot: value === "graphic" ? marker.graphicAssetSlot || graphics[0]?.slot || null : null } : {}), ...(key === "graphicAssetSlot" ? { kind: "graphic" } : {}) });
  return <fieldset><legend>{label}</legend><div className="studio-form-grid">
    <label>Marker type<select aria-label={`${label} type`} value={marker.kind} onChange={(event) => change("kind", event.target.value)}>{!outlineOnly ? <option value="graphic">Graphic</option> : null}<option value="outline">Outline</option>{!outlineOnly ? <option value="underline">Underline</option> : null}</select></label>
    {marker.kind === "graphic" ? <><label>Graphic<select aria-label={`${label} graphic`} value={marker.graphicAssetSlot || ""} onChange={(event) => change("graphicAssetSlot", event.target.value || null)}><option value="">Choose graphic</option>{graphics.map((graphic, index) => <option key={graphic.slot} value={graphic.slot}>Graphic {index + 1}</option>)}</select></label><label>Upload graphic<input aria-label={`${label} upload graphic`} type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => { onUpload(event.target.files?.[0]); event.target.value = ""; }} /></label></> : <><label>Color<input aria-label={`${label} color`} type="color" value={marker.color} onChange={(event) => change("color", event.target.value)} /></label><label>Line thickness<input aria-label={`${label} thickness`} type="number" min={1} max={192} value={marker.thickness} onChange={(event) => change("thickness", Number(event.target.value))} /></label></>}
    {!outlineOnly && marker.kind !== "graphic" ? <label>Upload graphic<input aria-label={`${label} upload graphic`} type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => { onUpload(event.target.files?.[0]); event.target.value = ""; }} /></label> : null}
    {marker.kind !== "outline" ? <label>Placement<select aria-label={`${label} placement`} value={marker.alignment} onChange={(event) => change("alignment", event.target.value)}><option value="bottom">Automatic bottom edge</option><option value="manual">Manual marking area</option></select></label> : null}
    <label>Marking height<input aria-label={`${label} height`} type="number" min={1} max={192} value={marker.height} onChange={(event) => change("height", Number(event.target.value))} /></label>
  </div></fieldset>;
}
