-- Generated by scripts/generate-students-book-page-expansion.mjs.
-- Additive current-authoring expansion. No authored page/activity/history rows
-- are rewritten. Historical canonical sources and released migrations are frozen.
-- Transaction owner: canonical migration runner (SQL and history in one commit).
create table if not exists builder_students_book_canonical_pages (
  page_key text primary key,
  unit_number integer not null check(unit_number between 1 and 10),
  width integer not null check(width>0),
  height integer not null check(height>0)
);
do $expansion$
declare component_id uuid; seed record; existing units%rowtype;
begin
  select component.id into strict component_id from book_components component join book_packages package on package.id=component.book_package_id where package.slug='ultimate-b2' and component.slug='ultimate-b2-students-book';
  -- Table-wide lock: blocks Unit writes for ALL components until runner commit.
  lock table units in share row exclusive mode;
  for seed in select * from (values
    (1,'Unit 1'),
    (2,'Unit 2'),
    (3,'Unit 3'),
    (4,'Unit 4'),
    (5,'Unit 5'),
    (6,'Unit 6'),
    (7,'Unit 7'),
    (8,'Unit 8'),
    (9,'Unit 9'),
    (10,'Unit 10')
  ) as seeds(number,title) loop
    if (select count(*) from units where book_component_id=component_id and (unit_number=seed.number or slug='unit-'||seed.number))>1 then raise exception 'students_book_unit_identity_conflict: Unit %',seed.number; end if;
    select * into existing from units where book_component_id=component_id and (unit_number=seed.number or slug='unit-'||seed.number);
    if existing.id is not null then
      if existing.unit_number is distinct from seed.number or existing.slug is distinct from 'unit-'||seed.number then raise exception 'students_book_unit_mapping_conflict: Unit %',seed.number; end if;
    else
      insert into units(book_component_id,title,slug,unit_number,sort_order) values(component_id,seed.title,'unit-'||seed.number,seed.number,seed.number);
    end if;
  end loop;
  for seed in select * from (values
    ('ultimate-b2-students-book/pages/ub2-sb-unit-1-part-1',1,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-1-part-2',1,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-1-part-3',1,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-1-part-4',1,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-1-part-5',1,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-1-part-6',1,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-1-part-7',1,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-1-part-8',1,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-1-part-9',1,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-1-part-10',1,581,794),
    ('ultimate-b2-students-book/pages/reading-19',2,581,794),
    ('ultimate-b2-students-book/pages/reading-20-21',2,1142,794),
    ('ultimate-b2-students-book/pages/vocabulary-22-23',2,1142,794),
    ('ultimate-b2-students-book/pages/grammar-24-25',2,1142,794),
    ('ultimate-b2-students-book/pages/listening-26',2,581,794),
    ('ultimate-b2-students-book/pages/speaking-27',2,581,794),
    ('ultimate-b2-students-book/pages/writing-28-29',2,1142,794),
    ('ultimate-b2-students-book/pages/review-30',2,581,794),
    ('ultimate-b2-students-book/pages/practice-31',2,581,794),
    ('ultimate-b2-students-book/pages/practice-32',2,581,794),
    ('ultimate-b2-students-book/pages/progress-check-33',2,581,794),
    ('ultimate-b2-students-book/pages/progress-check-34',2,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-3-part-1',3,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-3-part-2',3,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-3-part-3',3,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-3-part-4',3,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-3-part-5',3,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-3-part-6',3,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-3-part-7',3,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-3-part-8',3,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-3-part-9',3,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-3-part-10',3,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-4-part-1',4,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-4-part-2',4,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-4-part-3',4,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-4-part-4',4,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-4-part-5',4,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-4-part-6',4,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-4-part-7',4,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-4-part-8',4,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-4-part-9',4,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-4-part-10',4,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-4-part-11',4,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-4-part-12',4,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-5-part-1',5,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-5-part-2',5,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-5-part-3',5,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-5-part-4',5,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-5-part-5',5,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-5-part-6',5,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-5-part-7',5,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-5-part-8',5,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-5-part-9',5,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-5-part-10',5,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-6-part-1',6,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-6-part-2',6,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-6-part-3',6,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-6-part-4',6,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-6-part-5',6,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-6-part-6',6,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-6-part-7',6,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-6-part-8',6,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-6-part-9',6,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-6-part-10',6,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-6-part-11',6,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-6-part-12',6,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-7-part-1',7,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-7-part-2',7,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-7-part-3',7,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-7-part-4',7,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-7-part-5',7,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-7-part-6',7,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-7-part-7',7,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-7-part-8',7,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-7-part-9',7,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-7-part-10',7,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-8-part-1',8,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-8-part-2',8,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-8-part-3',8,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-8-part-4',8,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-8-part-5',8,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-8-part-6',8,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-8-part-7',8,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-8-part-8',8,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-8-part-9',8,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-8-part-10',8,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-8-part-11',8,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-8-part-12',8,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-9-part-1',9,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-9-part-2',9,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-9-part-3',9,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-9-part-4',9,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-9-part-5',9,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-9-part-6',9,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-9-part-7',9,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-9-part-8',9,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-9-part-9',9,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-9-part-10',9,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-10-part-1',10,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-10-part-2',10,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-10-part-3',10,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-10-part-4',10,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-10-part-5',10,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-10-part-6',10,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-10-part-7',10,1142,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-10-part-8',10,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-10-part-9',10,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-10-part-10',10,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-10-part-11',10,581,794),
    ('ultimate-b2-students-book/pages/ub2-sb-unit-10-part-12',10,581,794)
  ) as seeds(page_key,unit_number,width,height) loop
    if exists(select 1 from builder_students_book_canonical_pages page where page.page_key=seed.page_key and (page.unit_number<>seed.unit_number or page.width<>seed.width or page.height<>seed.height)) then raise exception 'students_book_canonical_identity_conflict: %',seed.page_key; end if;
    if not exists(select 1 from builder_students_book_canonical_pages page where page.page_key=seed.page_key) then
      insert into builder_students_book_canonical_pages values(seed.page_key,seed.unit_number,seed.width,seed.height);
    end if;
    if exists(select 1 from book_pages page left join units unit on unit.id=page.unit_id where page.stable_key=seed.page_key and (page.book_component_id is distinct from component_id or page.book_package_id is distinct from (select book_package_id from book_components where id=component_id) or page.unit_id is not null and (unit.book_component_id is distinct from component_id or unit.unit_number is distinct from seed.unit_number))) then raise exception 'students_book_page_unit_conflict: %',seed.page_key; end if;
  end loop;
end $expansion$;

-- Validate before casts; SQL NULL must never bypass a Students Book guard.
create or replace function builder_students_book_page_metadata_valid(metadata jsonb)
returns boolean language sql immutable as $$
  select coalesce(jsonb_typeof(metadata)='object'
    and jsonb_typeof(metadata->'label')='string' and length(metadata->>'label') between 1 and 200
    and jsonb_typeof(metadata->'sortOrder')='number' and (metadata->>'sortOrder') ~ '^-?[0-9]{1,9}$'
    and (not metadata ? 'printedLabel' or jsonb_typeof(metadata->'printedLabel')='string')
    and (not metadata ? 'unitId' or jsonb_typeof(metadata->'unitId')='string'), false)
$$;

create or replace function prepare_builder_component_page_upload(
  requested_book_slug text,requested_component_slug text,requested_page_key text,requested_mode text,
  requested_expected_revision bigint,requested_client_mutation_id uuid,requested_upload_id uuid,
  requested_request_sha256 text,requested_page_metadata jsonb,requested_file_descriptor jsonb,
  requested_staging_object_key text,actor_builder_user_id uuid,requested_expires_at timestamptz
)
returns table(outcome text,upload_id uuid,current_revision bigint,session_state text,staging_object_key text)
language plpgsql as $$
declare scope record; revision_row builder_component_page_revisions%rowtype; existing builder_component_page_upload_sessions%rowtype; page_row book_pages%rowtype; requested_unit uuid;
begin
  if not exists(select 1 from builder_users where id=actor_builder_user_id and status='active' and role='developer') then
    return query select 'unauthorized_actor',null::uuid,null::bigint,null::text,null::text; return;
  end if;
  select * into scope from resolve_builder_page_component(requested_book_slug,requested_component_slug);
  if scope.book_component_id is null or requested_page_key not like requested_component_slug||'/pages/%' then
    return query select 'resource_not_found',null::uuid,null::bigint,null::text,null::text; return;
  end if;
  if requested_component_slug='ultimate-b2-students-book' and (
    requested_page_key is null or requested_mode is null or requested_mode not in ('create','replace')
    or requested_expected_revision is null or requested_expected_revision<0
    or not builder_students_book_page_metadata_valid(requested_page_metadata)
  ) then return query select 'invalid_page_metadata',null::uuid,null::bigint,null::text,null::text; return; end if;
  if requested_page_metadata ? 'unitId' and coalesce(requested_page_metadata->>'unitId','')<>'' then
    begin requested_unit:=(requested_page_metadata->>'unitId')::uuid; exception when invalid_text_representation then
      return query select 'invalid_unit',null::uuid,null::bigint,null::text,null::text; return;
    end;
    if not exists(select 1 from units where id=requested_unit and book_component_id=scope.book_component_id and unit_number between 1 and 10 and slug='unit-'||unit_number) then
      return query select 'invalid_unit',null::uuid,null::bigint,null::text,null::text; return;
    end if;
  end if;
  insert into builder_component_page_revisions(book_component_id) values(scope.book_component_id) on conflict do nothing;
  select * into revision_row from builder_component_page_revisions where book_component_id=scope.book_component_id for update;
  select * into existing from builder_component_page_upload_sessions where book_component_id=scope.book_component_id and client_mutation_id=requested_client_mutation_id;
  if existing.id is not null then
    if existing.request_sha256<>requested_request_sha256 then
      return query select 'mutation_id_conflict',existing.id,revision_row.revision,existing.state,null::text;
    else
      return query select 'idempotent',existing.id,revision_row.revision,existing.state,existing.staging_object_key;
    end if;
    return;
  end if;
  if revision_row.revision<>requested_expected_revision then
    return query select 'revision_conflict',null::uuid,revision_row.revision,null::text,null::text; return;
  end if;
  select * into page_row from book_pages where book_component_id=scope.book_component_id and stable_key=requested_page_key;
  if requested_book_slug='ultimate-b2' and requested_component_slug='ultimate-b2-students-book' then
    if exists(select 1 from builder_students_book_canonical_pages where page_key=requested_page_key) then
      if requested_mode<>'replace' then return query select 'operation_not_allowed',null::uuid,revision_row.revision,null::text,null::text; return; end if;
      if exists(select 1 from builder_students_book_canonical_pages where page_key=requested_page_key and (requested_page_metadata->>'baselineWidth' is distinct from width::text or requested_page_metadata->>'baselineHeight' is distinct from height::text)) then
        return query select 'canonical_dimensions_conflict',null::uuid,revision_row.revision,null::text,null::text; return;
      end if;
      if requested_unit is not null and not exists(select 1 from units unit join builder_students_book_canonical_pages canonical on canonical.unit_number=unit.unit_number where canonical.page_key=requested_page_key and unit.id=requested_unit) then
        return query select 'invalid_unit',null::uuid,revision_row.revision,null::text,null::text; return;
      end if;
    elsif requested_page_key ~ '^ultimate-b2-students-book/pages/sb-page-[a-f0-9]{32}$' then
      if requested_mode='create' then
        if page_row.id is not null then return query select 'page_state_conflict',null::uuid,revision_row.revision,null::text,null::text; return; end if;
        if requested_unit is null then return query select 'invalid_unit',null::uuid,revision_row.revision,null::text,null::text; return; end if;
      elsif requested_mode<>'replace' or page_row.id is null or coalesce(page_row.source_metadata->>'is_active','false')<>'true' then
        return query select 'page_state_conflict',null::uuid,revision_row.revision,null::text,null::text; return;
      end if;
    else return query select 'invalid_students_book_page_identity',null::uuid,revision_row.revision,null::text,null::text; return;
    end if;
    if coalesce(page_row.source_metadata->>'is_deleted','false')='true' or coalesce(page_row.source_metadata->>'is_permanently_deleted','false')='true' then
      return query select 'page_state_conflict',null::uuid,revision_row.revision,null::text,null::text; return;
    end if;
  end if;
  if (requested_book_slug,requested_component_slug) in (
    ('ultimate-b2','ultimate-b2-workbook'),
    ('ultimate-b2','ultimate-b2-grammar-book'),
    ('ultimate-b1','ultimate-b1-students-book'),
    ('ultimate-b1','ultimate-b1-workbook'),
    ('ultimate-b1','ultimate-b1-grammar-book'),
    ('ultimate-b1-plus','ultimate-b1-plus-students-book'),
    ('ultimate-b1-plus','ultimate-b1-plus-workbook'),
    ('ultimate-b1-plus','ultimate-b1-plus-grammar-book')
  ) and (
    (requested_mode='create' and page_row.id is not null and coalesce(page_row.source_metadata->>'is_active','false')='true')
    or (requested_mode='replace' and (page_row.id is null or coalesce(page_row.source_metadata->>'is_active','false')<>'true'))
  ) then return query select 'page_state_conflict',null::uuid,revision_row.revision,null::text,null::text; return; end if;
  insert into builder_component_page_upload_sessions(
    id,book_package_id,book_component_id,page_key,upload_mode,expected_revision,client_mutation_id,request_sha256,
    page_metadata,file_descriptor,staging_object_key,created_by_builder_user_id,expires_at
  ) values(requested_upload_id,scope.book_package_id,scope.book_component_id,requested_page_key,requested_mode,requested_expected_revision,
    requested_client_mutation_id,requested_request_sha256,requested_page_metadata,requested_file_descriptor,requested_staging_object_key,actor_builder_user_id,requested_expires_at);
  return query select 'prepared',requested_upload_id,revision_row.revision,'prepared',requested_staging_object_key;
end $$;

create or replace function complete_builder_component_page_upload(
  requested_upload_id uuid,actor_builder_user_id uuid,requested_object_key text,requested_storage_bucket text,
  requested_mime_type text,requested_byte_size bigint,requested_checksum text,requested_width int,requested_height int
)
returns table(outcome text,page_id uuid,asset_id uuid,revision bigint) language plpgsql as $$
declare session builder_component_page_upload_sessions%rowtype; revision_row builder_component_page_revisions%rowtype; page_row book_pages%rowtype;
  edition book_editions%rowtype; created_asset_id uuid; package_slug text; component_slug text; page_slug text; student_component boolean; requested_unit uuid;
begin
  select upload_session.* into session from builder_component_page_upload_sessions upload_session where upload_session.id=requested_upload_id for update;
  if session.id is null or session.created_by_builder_user_id<>actor_builder_user_id or session.state<>'finalizing' then raise exception 'page upload session cannot be completed'; end if;
  if requested_mime_type not in ('image/png','image/jpeg','image/webp') or requested_byte_size<1 or requested_checksum!~'^[a-f0-9]{64}$' or requested_width<1 or requested_height<1 then raise exception 'page upload metadata is invalid'; end if;
  select book_package.slug,component.slug into package_slug,component_slug from book_packages book_package join book_components component on component.book_package_id=book_package.id where component.id=session.book_component_id;
  student_component:=component_slug='ultimate-b2-students-book' and exists(select 1 from builder_students_book_canonical_pages where page_key=session.page_key);
  if student_component and exists(select 1 from builder_students_book_canonical_pages where page_key=session.page_key and (width<>requested_width or height<>requested_height)) then raise exception 'canonical page dimensions conflict'; end if;
  if component_slug='ultimate-b2-students-book' then
    if package_slug is distinct from 'ultimate-b2' or not exists(select 1 from book_components where id=session.book_component_id and book_package_id=session.book_package_id)
      or not builder_students_book_page_metadata_valid(session.page_metadata)
      or requested_mime_type is null or requested_byte_size is null or requested_checksum is null or requested_width is null or requested_height is null
      or (not student_component and session.page_key !~ '^ultimate-b2-students-book/pages/sb-page-[a-f0-9]{32}$') then raise exception 'page upload metadata is invalid'; end if;
  end if;
  page_slug:=substring(session.page_key from char_length(component_slug)+8);
  if session.page_metadata ? 'unitId' and coalesce(session.page_metadata->>'unitId','')<>'' then
    requested_unit:=(session.page_metadata->>'unitId')::uuid;
    if not exists(select 1 from units where id=requested_unit and book_component_id=session.book_component_id and unit_number between 1 and 10 and slug='unit-'||unit_number) then raise exception 'page upload unit is invalid'; end if;
  end if;
  if component_slug='ultimate-b2-students-book' then
    if student_component and requested_unit is not null and not exists(select 1 from units unit join builder_students_book_canonical_pages canonical on canonical.unit_number=unit.unit_number where canonical.page_key=session.page_key and unit.id=requested_unit) then raise exception 'canonical page unit conflict'; end if;
    if not student_component and session.upload_mode='create' and requested_unit is null then raise exception 'page upload unit is invalid'; end if;
  end if;
  select page_revision.* into revision_row from builder_component_page_revisions page_revision where page_revision.book_component_id=session.book_component_id for update;
  if revision_row.revision<>session.expected_revision then raise exception 'page revision changed during finalize'; end if;
  select component_page.* into page_row from book_pages component_page where component_page.book_component_id=session.book_component_id and component_page.stable_key=session.page_key for update;
  if component_slug='ultimate-b2-students-book' and not student_component and (
    session.upload_mode='create' and page_row.id is not null
    or session.upload_mode='replace' and (page_row.id is null or coalesce(page_row.source_metadata->>'is_active','false')<>'true')
  ) then raise exception 'page upload identity conflict'; end if;
  if page_row.id is null then
    insert into book_pages as created_page(book_package_id,book_component_id,unit_id,stable_key,label,sort_order,source_metadata)
    values(session.book_package_id,session.book_component_id,requested_unit,session.page_key,session.page_metadata->>'label',(session.page_metadata->>'sortOrder')::int,
      jsonb_build_object('source','builder-pages','is_override',student_component,'has_image_override',student_component,'has_metadata_override',false,'is_active',true,'is_deleted',false,'printed_label',coalesce(session.page_metadata->>'printedLabel',''),'original_filename',session.file_descriptor->>'name')) returning created_page.* into page_row;
  else
    if coalesce(page_row.source_metadata->>'is_deleted','false')='true' or coalesce(page_row.source_metadata->>'is_permanently_deleted','false')='true' then raise exception 'page upload target is inactive'; end if;
    update book_pages as updated_page set label=case when student_component and updated_page.source_metadata->>'has_metadata_override'='true' then updated_page.label else session.page_metadata->>'label' end,
      sort_order=case when student_component and updated_page.source_metadata->>'has_metadata_override'='true' then updated_page.sort_order else (session.page_metadata->>'sortOrder')::int end,
      unit_id=case when requested_unit is not null then requested_unit else updated_page.unit_id end,
      source_metadata=updated_page.source_metadata||jsonb_build_object('source','builder-pages','is_override',student_component or coalesce((updated_page.source_metadata->>'has_metadata_override')::boolean,false),'has_image_override',student_component,'is_active',true,'is_deleted',false,'printed_label',case when student_component and updated_page.source_metadata->>'has_metadata_override'='true' then coalesce(updated_page.source_metadata->>'printed_label','') else coalesce(session.page_metadata->>'printedLabel','') end,'original_filename',session.file_descriptor->>'name'),updated_at=now()
    where updated_page.id=page_row.id returning updated_page.* into page_row;
  end if;
  insert into book_editions as page_edition(book_package_id,edition_identifier,title,status,source_metadata)
  values(session.book_package_id,'builder-pages','Builder page assets','draft','{"source":"builder-pages"}'::jsonb)
  on conflict(book_package_id,edition_identifier) do update set updated_at=now() returning page_edition.* into edition;
  update book_assets page_asset set publication_status='archived',updated_at=now() where page_asset.page_id=page_row.id and page_asset.asset_role='page_image' and page_asset.publication_status='draft';
  select existing_asset.id into created_asset_id from book_assets existing_asset where existing_asset.storage_bucket=requested_storage_bucket and existing_asset.object_key=requested_object_key;
  if created_asset_id is not null then
    update book_assets managed_asset set publication_status='draft',unit_id=page_row.unit_id,updated_at=now()
    where managed_asset.id=created_asset_id and managed_asset.book_package_id=session.book_package_id and managed_asset.book_component_id=session.book_component_id and managed_asset.page_id=page_row.id
      and managed_asset.asset_role='page_image' and managed_asset.mime_type=requested_mime_type and managed_asset.byte_size=requested_byte_size and managed_asset.checksum_sha256=requested_checksum
      and managed_asset.width=requested_width and managed_asset.height=requested_height and managed_asset.storage_profile='private' and managed_asset.access_level='internal';
    if not found then raise exception 'page managed asset identity conflict'; end if;
  else
    insert into book_assets as created_asset(book_package_id,edition_id,book_component_id,unit_id,page_id,activity_id,stable_logical_key,asset_role,object_key,storage_profile,storage_bucket,mime_type,byte_size,checksum_sha256,width,height,edition_identifier,version,publication_status,access_level,source_metadata)
    values(session.book_package_id,edition.id,session.book_component_id,page_row.unit_id,page_row.id,null,package_slug||'.builder-pages.'||component_slug||'.'||page_slug,'page_image',requested_object_key,'private',requested_storage_bucket,requested_mime_type,requested_byte_size,requested_checksum,requested_width,requested_height,'builder-pages',page_slug,'draft','internal',jsonb_build_object('upload_session_id',session.id,'original_filename',session.file_descriptor->>'name')) returning created_asset.id into created_asset_id;
  end if;
  update builder_component_page_revisions page_revision set revision=page_revision.revision+1,updated_at=now() where page_revision.book_component_id=session.book_component_id returning page_revision.* into revision_row;
  update builder_component_page_upload_sessions upload_session set state='completed',resulting_page_id=page_row.id,resulting_asset_id=created_asset_id,resulting_revision=revision_row.revision,finalized_at=now(),updated_at=now() where upload_session.id=session.id;
  insert into builder_audit_log(builder_user_id,action,target_type,target_id,metadata) values(actor_builder_user_id,'component_page_asset_finalized','book_page',page_row.id::text,jsonb_build_object('component_slug',component_slug,'page_key',session.page_key,'revision',revision_row.revision));
  return query select 'saved',page_row.id,created_asset_id,revision_row.revision;
end $$;

create or replace function mutate_builder_component_page(
  requested_book_slug text,requested_component_slug text,requested_page_key text,requested_action text,requested_expected_revision bigint,
  requested_client_mutation_id uuid,requested_page_metadata jsonb,actor_builder_user_id uuid
)
returns table(outcome text,current_revision bigint) language plpgsql as $$
declare scope record; revision_row builder_component_page_revisions%rowtype; page_row book_pages%rowtype; existing builder_component_page_mutations%rowtype; request_value jsonb; requested_unit uuid;
begin
  if not exists(select 1 from builder_users where id=actor_builder_user_id and status='active' and role='developer') then return query select 'unauthorized_actor',null::bigint; return; end if;
  select * into scope from resolve_builder_page_component(requested_book_slug,requested_component_slug);
  if scope.book_component_id is null or requested_page_key not like requested_component_slug||'/pages/%' then return query select 'resource_not_found',null::bigint; return; end if;
  if requested_component_slug='ultimate-b2-students-book' and requested_action in ('metadata','reorder') and not builder_students_book_page_metadata_valid(requested_page_metadata) then return query select 'invalid_page_metadata',null::bigint; return; end if;
  if requested_page_metadata ? 'unitId' and coalesce(requested_page_metadata->>'unitId','')<>'' then
    begin requested_unit:=(requested_page_metadata->>'unitId')::uuid; exception when invalid_text_representation then return query select 'invalid_unit',null::bigint; return; end;
    if (requested_component_slug='ultimate-b2-students-book' and exists(select 1 from builder_students_book_canonical_pages where page_key=requested_page_key)) or not exists(select 1 from units where id=requested_unit and book_component_id=scope.book_component_id and unit_number between 1 and 10 and slug='unit-'||unit_number) then return query select 'invalid_unit',null::bigint; return; end if;
  end if;
  insert into builder_component_page_revisions(book_component_id) values(scope.book_component_id) on conflict do nothing;
  select * into revision_row from builder_component_page_revisions where book_component_id=scope.book_component_id for update;
  request_value:=jsonb_build_object('pageKey',requested_page_key,'action',requested_action,'metadata',requested_page_metadata);
  select * into existing from builder_component_page_mutations where book_component_id=scope.book_component_id and client_mutation_id=requested_client_mutation_id;
  if existing.client_mutation_id is not null then return query select case when existing.request_payload=request_value then 'idempotent' else 'mutation_id_conflict' end,existing.resulting_revision; return; end if;
  if revision_row.revision<>requested_expected_revision then return query select 'revision_conflict',revision_row.revision; return; end if;
  select * into page_row from book_pages where book_component_id=scope.book_component_id and stable_key=requested_page_key for update;
  if page_row.id is null then return query select 'page_not_found',revision_row.revision; return; end if;
  if coalesce(page_row.source_metadata->>'is_deleted','false')='true' or coalesce(page_row.source_metadata->>'is_permanently_deleted','false')='true' then return query select 'page_state_conflict',revision_row.revision; return; end if;
  if requested_action in ('metadata','reorder') then
    update book_pages set label=requested_page_metadata->>'label',sort_order=(requested_page_metadata->>'sortOrder')::int,
      unit_id=case when requested_unit is not null then requested_unit else unit_id end,
      source_metadata=source_metadata||jsonb_build_object('printed_label',coalesce(requested_page_metadata->>'printedLabel',''),'has_metadata_override',(requested_component_slug='ultimate-b2-students-book' and exists(select 1 from builder_students_book_canonical_pages where page_key=requested_page_key)),'is_override',(requested_component_slug='ultimate-b2-students-book' and exists(select 1 from builder_students_book_canonical_pages where page_key=requested_page_key)) or coalesce((source_metadata->>'is_override')::boolean,false)),updated_at=now() where id=page_row.id;
    update book_assets set unit_id=(select unit_id from book_pages where id=page_row.id),updated_at=now() where page_id=page_row.id and publication_status='draft';
  elsif requested_action='restore-image' and (requested_component_slug='ultimate-b2-students-book' and exists(select 1 from builder_students_book_canonical_pages where page_key=requested_page_key)) then
    update book_assets set publication_status='archived',updated_at=now() where page_id=page_row.id and asset_role='page_image' and publication_status='draft';
    update book_pages set source_metadata=source_metadata||jsonb_build_object('has_image_override',false,'is_override',coalesce((source_metadata->>'has_metadata_override')::boolean,false)),updated_at=now() where id=page_row.id;
  else return query select 'operation_not_allowed',revision_row.revision; return; end if;
  update builder_component_page_revisions set revision=revision+1,updated_at=now() where book_component_id=scope.book_component_id returning * into revision_row;
  insert into builder_component_page_mutations(book_component_id,client_mutation_id,request_payload,resulting_revision,created_by_builder_user_id) values(scope.book_component_id,requested_client_mutation_id,request_value,revision_row.revision,actor_builder_user_id);
  insert into builder_audit_log(builder_user_id,action,target_type,target_id,metadata) values(actor_builder_user_id,'component_page_'||replace(requested_action,'-','_'),'book_page',page_row.id::text,jsonb_build_object('component_slug',requested_component_slug,'revision',revision_row.revision));
  return query select 'saved',revision_row.revision;
end $$;

create or replace function delete_builder_component_page_lifecycle(
  requested_book_slug text,requested_component_slug text,requested_page_key text,
  requested_expected_revision bigint,requested_expected_hotspot_revision bigint,
  requested_client_mutation_id uuid,requested_page_metadata jsonb,
  requested_hotspot_schema_version text,requested_hotspot_payload jsonb,requested_hotspot_sha256 text,
  requested_removed_hotspot_count int,requested_preserved_activity_count int,actor_builder_user_id uuid
)
returns table(outcome text,current_revision bigint,hotspot_revision bigint,removed_hotspot_count int,preserved_activity_count int)
language plpgsql as $$
declare
  scope record; revision_row builder_component_page_revisions%rowtype; page_row book_pages%rowtype;
  hotspot_document builder_component_documents%rowtype; existing builder_component_page_mutations%rowtype;
  request_value jsonb; page_slug text; next_hotspot_revision bigint; resolved_unit_id uuid; restorable_asset_id uuid;
begin
  if not exists(select 1 from builder_users where id=actor_builder_user_id and status='active' and role='developer') then return query select 'unauthorized_actor',null::bigint,null::bigint,0,0; return; end if;
  select * into scope from resolve_builder_page_component(requested_book_slug,requested_component_slug);
  if scope.book_component_id is null or requested_page_key not like requested_component_slug||'/pages/%' then return query select 'resource_not_found',null::bigint,null::bigint,0,0; return; end if;
  if requested_hotspot_schema_version!~'^[0-9]+\.[0-9]+$' or requested_hotspot_sha256!~'^[a-f0-9]{64}$'
    or jsonb_typeof(requested_hotspot_payload)<>'object' or jsonb_typeof(requested_hotspot_payload->'pages')<>'object'
    or requested_hotspot_payload->>'schemaVersion'<>requested_hotspot_schema_version or requested_hotspot_payload->>'packageSlug'<>requested_book_slug
    or requested_removed_hotspot_count<0 or requested_preserved_activity_count<0 then return query select 'invalid_hotspot_projection',null::bigint,null::bigint,0,0; return; end if;
  page_slug:=substring(requested_page_key from char_length(requested_component_slug)+8);
  if requested_hotspot_payload->'pages' ? page_slug then return query select 'invalid_hotspot_projection',null::bigint,null::bigint,0,0; return; end if;
  insert into builder_component_page_revisions(book_component_id) values(scope.book_component_id) on conflict do nothing;
  select * into revision_row from builder_component_page_revisions where book_component_id=scope.book_component_id for update;
  select * into hotspot_document from builder_component_documents where book_component_id=scope.book_component_id and document_type='hotspots' and document_key='default' for update;
  next_hotspot_revision:=coalesce(hotspot_document.revision,0);
  request_value:=jsonb_build_object('pageKey',requested_page_key,'action','delete','expectedRevision',requested_expected_revision,'expectedHotspotRevision',requested_expected_hotspot_revision,'pageMetadata',requested_page_metadata,'hotspotSha256',requested_hotspot_sha256,'removedHotspotCount',requested_removed_hotspot_count,'preservedActivityCount',requested_preserved_activity_count);
  select * into existing from builder_component_page_mutations where book_component_id=scope.book_component_id and client_mutation_id=requested_client_mutation_id;
  if existing.client_mutation_id is not null then return query select case when existing.request_payload=request_value then 'idempotent' else 'mutation_id_conflict' end,existing.resulting_revision,coalesce(existing.resulting_hotspot_revision,next_hotspot_revision),coalesce(existing.removed_hotspot_count,0),coalesce(existing.preserved_activity_count,0); return; end if;
  if revision_row.revision<>requested_expected_revision then return query select 'revision_conflict',revision_row.revision,next_hotspot_revision,0,0; return; end if;
  if next_hotspot_revision<>requested_expected_hotspot_revision then return query select 'hotspot_revision_conflict',revision_row.revision,next_hotspot_revision,0,0; return; end if;
  if exists(select 1 from book_media_assets where package_slug=requested_book_slug and component_slug=requested_component_slug and page_id=page_slug)
    or exists(select 1 from builder_component_documents where book_component_id=scope.book_component_id
      and document_type not in ('hotspots','native_activity_index','native_activity_public','native_activity_teacher','activity_lifecycle','open_response')
      and not (requested_book_slug='ultimate-b2' and requested_component_slug='ultimate-b2-students-book' and document_type='unit_extras' and document_key='default')
      and payload::text like '%'||page_slug||'%') then return query select 'unsupported_page_reference',revision_row.revision,next_hotspot_revision,0,0; return; end if;
  select * into page_row from book_pages where book_component_id=scope.book_component_id and stable_key=requested_page_key for update;
  if page_row.id is null and (requested_component_slug='ultimate-b2-students-book' and exists(select 1 from builder_students_book_canonical_pages where page_key=requested_page_key)) then
    select id into resolved_unit_id from units where book_component_id=scope.book_component_id and unit_number=(select canonical.unit_number from builder_students_book_canonical_pages canonical where canonical.page_key=requested_page_key) limit 1;
    insert into book_pages(book_package_id,book_component_id,unit_id,stable_key,label,sort_order,source_metadata)
    values(scope.book_package_id,scope.book_component_id,resolved_unit_id,requested_page_key,requested_page_metadata->>'label',(requested_page_metadata->>'sortOrder')::int,
      jsonb_build_object('source','builder-pages','is_override',false,'has_image_override',false,'has_metadata_override',false,'is_active',false,'is_deleted',true,'is_permanently_deleted',false,'printed_label',coalesce(requested_page_metadata->>'printedLabel',''),'removed_hotspot_count',requested_removed_hotspot_count,'preserved_activity_count',requested_preserved_activity_count,'deleted_at',now())) returning * into page_row;
  elsif page_row.id is null then return query select 'page_not_found',revision_row.revision,next_hotspot_revision,0,0; return;
  elsif coalesce(page_row.source_metadata->>'is_deleted','false')='true' or coalesce(page_row.source_metadata->>'is_permanently_deleted','false')='true' or (not (requested_component_slug='ultimate-b2-students-book' and exists(select 1 from builder_students_book_canonical_pages where page_key=requested_page_key)) and coalesce(page_row.source_metadata->>'is_active','false')<>'true') then return query select 'page_state_conflict',revision_row.revision,next_hotspot_revision,0,0; return; end if;
  if exists(select 1 from book_assets where page_id=page_row.id and asset_role<>'page_image' and publication_status<>'archived') then return query select 'unsupported_page_reference',revision_row.revision,next_hotspot_revision,0,0; return; end if;
  select id into restorable_asset_id from book_assets where page_id=page_row.id and book_component_id=scope.book_component_id and asset_role='page_image' and publication_status='draft' and storage_profile='private' and access_level='internal' order by updated_at desc,id limit 1;
  if requested_removed_hotspot_count>0 then
    next_hotspot_revision:=next_hotspot_revision+1;
    if hotspot_document.id is null then
      insert into builder_component_documents(book_package_id,book_component_id,document_type,document_key,schema_version,revision,payload,payload_sha256,created_by_builder_user_id,updated_by_builder_user_id)
      values(scope.book_package_id,scope.book_component_id,'hotspots','default',requested_hotspot_schema_version,next_hotspot_revision,requested_hotspot_payload,requested_hotspot_sha256,actor_builder_user_id,actor_builder_user_id) returning * into hotspot_document;
    else update builder_component_documents set schema_version=requested_hotspot_schema_version,revision=next_hotspot_revision,payload=requested_hotspot_payload,payload_sha256=requested_hotspot_sha256,updated_by_builder_user_id=actor_builder_user_id,updated_at=now() where id=hotspot_document.id returning * into hotspot_document; end if;
    insert into builder_component_document_revisions(document_id,revision,payload,payload_sha256,changed_by_builder_user_id,client_mutation_id) values(hotspot_document.id,next_hotspot_revision,requested_hotspot_payload,requested_hotspot_sha256,actor_builder_user_id,requested_client_mutation_id);
  end if;
  update book_assets set publication_status='archived',updated_at=now() where page_id=page_row.id and asset_role='page_image' and publication_status='draft';
  update book_pages set source_metadata=source_metadata||jsonb_strip_nulls(jsonb_build_object('is_active',false,'is_deleted',true,'is_permanently_deleted',false,'removed_hotspot_count',requested_removed_hotspot_count,'preserved_activity_count',requested_preserved_activity_count,'restorable_asset_id',restorable_asset_id::text,'deleted_at',now())),updated_at=now() where id=page_row.id;
  update builder_component_page_revisions set revision=revision+1,updated_at=now() where book_component_id=scope.book_component_id returning * into revision_row;
  insert into builder_component_page_mutations(book_component_id,client_mutation_id,request_payload,resulting_revision,resulting_hotspot_revision,removed_hotspot_count,preserved_activity_count,created_by_builder_user_id) values(scope.book_component_id,requested_client_mutation_id,request_value,revision_row.revision,next_hotspot_revision,requested_removed_hotspot_count,requested_preserved_activity_count,actor_builder_user_id);
  insert into builder_audit_log(builder_user_id,action,target_type,target_id,metadata) values(actor_builder_user_id,'component_page_deleted','book_page',page_row.id::text,jsonb_build_object('component_slug',requested_component_slug,'page_key',requested_page_key,'page_revision',revision_row.revision,'hotspot_revision',next_hotspot_revision,'removed_hotspot_count',requested_removed_hotspot_count,'preserved_activity_count',requested_preserved_activity_count));
  return query select 'saved',revision_row.revision,next_hotspot_revision,requested_removed_hotspot_count,requested_preserved_activity_count;
end $$;

create or replace function restore_builder_component_page(
  requested_book_slug text,requested_component_slug text,requested_page_key text,requested_expected_revision bigint,
  requested_client_mutation_id uuid,actor_builder_user_id uuid
)
returns table(outcome text,current_revision bigint) language plpgsql as $$
declare scope record; revision_row builder_component_page_revisions%rowtype; page_row book_pages%rowtype; existing builder_component_page_mutations%rowtype; request_value jsonb; restore_asset uuid; candidate_count int;
begin
  if not exists(select 1 from builder_users where id=actor_builder_user_id and status='active' and role='developer') then return query select 'unauthorized_actor',null::bigint; return; end if;
  select * into scope from resolve_builder_page_component(requested_book_slug,requested_component_slug);
  if scope.book_component_id is null or requested_page_key not like requested_component_slug||'/pages/%' then return query select 'resource_not_found',null::bigint; return; end if;
  insert into builder_component_page_revisions(book_component_id) values(scope.book_component_id) on conflict do nothing;
  select * into revision_row from builder_component_page_revisions where book_component_id=scope.book_component_id for update;
  request_value:=jsonb_build_object('pageKey',requested_page_key,'action','restore-page','expectedRevision',requested_expected_revision);
  select * into existing from builder_component_page_mutations where book_component_id=scope.book_component_id and client_mutation_id=requested_client_mutation_id;
  if existing.client_mutation_id is not null then return query select case when existing.request_payload=request_value then 'idempotent' else 'mutation_id_conflict' end,existing.resulting_revision; return; end if;
  if revision_row.revision<>requested_expected_revision then return query select 'revision_conflict',revision_row.revision; return; end if;
  select * into page_row from book_pages where book_component_id=scope.book_component_id and stable_key=requested_page_key for update;
  if page_row.id is null then return query select 'page_not_found',revision_row.revision; return; end if;
  if coalesce(page_row.source_metadata->>'is_permanently_deleted','false')='true' then return query select 'page_permanently_deleted',revision_row.revision; return; end if;
  if coalesce(page_row.source_metadata->>'is_deleted','false')<>'true' then return query select 'page_state_conflict',revision_row.revision; return; end if;
  if coalesce(page_row.source_metadata->>'restorable_asset_id','')<>'' then
    begin restore_asset:=(page_row.source_metadata->>'restorable_asset_id')::uuid; exception when invalid_text_representation then return query select 'restorable_asset_unavailable',revision_row.revision; return; end;
  elsif not (requested_component_slug='ultimate-b2-students-book' and exists(select 1 from builder_students_book_canonical_pages where page_key=requested_page_key)) then
    select count(*)::int,(array_agg(id order by id))[1] into candidate_count,restore_asset from book_assets where page_id=page_row.id and book_component_id=scope.book_component_id and book_package_id=scope.book_package_id and asset_role='page_image' and publication_status='archived' and storage_profile='private' and access_level='internal' and updated_at=page_row.updated_at;
    if candidate_count<>1 then select count(*)::int,(array_agg(id order by id))[1] into candidate_count,restore_asset from book_assets where page_id=page_row.id and book_component_id=scope.book_component_id and book_package_id=scope.book_package_id and asset_role='page_image' and publication_status='archived' and storage_profile='private' and access_level='internal'; end if;
    if candidate_count<>1 then return query select 'restorable_asset_unavailable',revision_row.revision; return; end if;
  end if;
  if restore_asset is not null then
    update book_assets set publication_status='archived',updated_at=now() where page_id=page_row.id and asset_role='page_image' and publication_status='draft';
    update book_assets set publication_status='draft',unit_id=page_row.unit_id,updated_at=now() where id=restore_asset and page_id=page_row.id and book_component_id=scope.book_component_id and book_package_id=scope.book_package_id and asset_role='page_image' and publication_status='archived' and storage_profile='private' and access_level='internal';
    if not found then return query select 'restorable_asset_unavailable',revision_row.revision; return; end if;
  end if;
  update book_pages set source_metadata=(source_metadata-'deleted_at')||jsonb_build_object('is_active',true,'is_deleted',false,'is_permanently_deleted',false,'has_image_override',case when (requested_component_slug='ultimate-b2-students-book' and exists(select 1 from builder_students_book_canonical_pages where page_key=requested_page_key)) then restore_asset is not null else coalesce((source_metadata->>'has_image_override')::boolean,false) end,'is_override',case when (requested_component_slug='ultimate-b2-students-book' and exists(select 1 from builder_students_book_canonical_pages where page_key=requested_page_key)) then restore_asset is not null or coalesce((source_metadata->>'has_metadata_override')::boolean,false) else coalesce((source_metadata->>'is_override')::boolean,false) end),updated_at=now() where id=page_row.id;
  update builder_component_page_revisions set revision=revision+1,updated_at=now() where book_component_id=scope.book_component_id returning * into revision_row;
  insert into builder_component_page_mutations(book_component_id,client_mutation_id,request_payload,resulting_revision,created_by_builder_user_id) values(scope.book_component_id,requested_client_mutation_id,request_value,revision_row.revision,actor_builder_user_id);
  insert into builder_audit_log(builder_user_id,action,target_type,target_id,metadata) values(actor_builder_user_id,'component_page_restored','book_page',page_row.id::text,jsonb_build_object('component_slug',requested_component_slug,'revision',revision_row.revision,'hotspots_restored',false,'asset_id',restore_asset));
  return query select 'saved',revision_row.revision;
end $$;

create or replace function validate_builder_release_asset_pin()
returns trigger language plpgsql as $$
declare
  release_row book_component_releases%rowtype; asset_row book_assets%rowtype;
  package_slug text; component_slug text; page_key text; unit_slug text;
  expected_key text; expected_source_role text; unit_extension text; unit_mime text;
begin
  select * into release_row from book_component_releases where id=new.component_release_id;
  select * into asset_row from book_assets where id=new.book_asset_id;
  select package.slug,component.slug into package_slug,component_slug from book_packages package
  join book_components component on component.book_package_id=package.id
  where package.id=new.book_package_id and component.id=new.book_component_id;
  if release_row.id is null or asset_row.id is null or package_slug is null or release_row.asset_storage_mode<>'pinned-source-v1'
    or release_row.book_package_id<>new.book_package_id or release_row.book_component_id<>new.book_component_id
    or asset_row.book_package_id<>new.book_package_id or asset_row.book_component_id<>new.book_component_id
  then raise exception using errcode='PZ001',message='release_pin_integrity_failed'; end if;
  expected_source_role:=case when new.asset_role='managed_page_image' then 'page_image' else new.asset_role end;
  if new.source_asset_role<>expected_source_role or asset_row.asset_role<>expected_source_role
    or asset_row.checksum_sha256<>new.checksum_sha256 or asset_row.byte_size<>new.byte_size
    or asset_row.mime_type<>new.media_type or asset_row.storage_profile<>new.storage_profile
    or asset_row.storage_bucket<>new.storage_bucket or asset_row.object_key<>new.object_key
    or asset_row.publication_status<>'draft' or asset_row.access_level<>'internal'
    or new.pin_sha256<>builder_release_asset_pin_sha256(new.book_asset_id,new.asset_role,new.source_asset_role,new.checksum_sha256,new.byte_size,new.media_type,new.extension,new.storage_profile,new.storage_bucket,new.object_key,new.source_owner_key,new.source_asset_slot)
    or not exists(select 1 from jsonb_array_elements(release_row.asset_manifest) descriptor where descriptor->>'sha256'=new.checksum_sha256 and descriptor->>'extension'=new.extension and descriptor->>'mediaType'=new.media_type and descriptor->>'role'=new.asset_role)
  then raise exception using errcode='PZ001',message='release_pin_integrity_failed'; end if;
  if new.asset_role='managed_page_image' then
    select stable_key into page_key from book_pages where id=asset_row.page_id and book_component_id=new.book_component_id;
    expected_key:='builder-page-assets/'||package_slug||'/'||component_slug||'/'||new.source_owner_key||'/assets/'||new.checksum_sha256||'.'||new.extension;
    if page_key<>component_slug||'/pages/'||new.source_owner_key or new.source_asset_slot<>'' or new.object_key<>expected_key then raise exception using errcode='PZ001',message='release_pin_integrity_failed'; end if;
  elsif new.asset_role='activity_font' then
    expected_key:='builder-font-library/'||package_slug||'/'||component_slug||'/'||new.checksum_sha256||'.ttf';
    if new.media_type<>'font/ttf' or new.extension<>'ttf' or new.source_owner_key<>'component' or new.source_asset_slot<>''
      or asset_row.unit_id is not null or asset_row.page_id is not null or asset_row.activity_id is not null
      or asset_row.source_metadata->>'font_library_scope'<>'component' or (new.object_key<>expected_key and new.object_key<>'builder-font-library/'||package_slug||'/'||component_slug||'/assets/'||new.checksum_sha256||'.ttf')
    then raise exception using errcode='PZ001',message='release_pin_integrity_failed'; end if;
  elsif new.asset_role in ('unit_extra_video','unit_extra_audio') then
    unit_extension:=case when new.asset_role='unit_extra_audio' then 'mp3' else 'mp4' end;
    unit_mime:=case when new.asset_role='unit_extra_audio' then 'audio/mpeg' else 'video/mp4' end;
    select slug into unit_slug from units where id=asset_row.unit_id and book_component_id=new.book_component_id;
    expected_key:='builder-unit-extra-assets/'||package_slug||'/'||component_slug||'/'||unit_slug||'/'||new.source_owner_key||'/assets/'||new.checksum_sha256||'.'||unit_extension;
    if new.media_type<>unit_mime or new.extension<>unit_extension or asset_row.page_id is not null or asset_row.activity_id is not null
      or asset_row.source_metadata->>'unit_extra_item_id'<>new.source_owner_key or asset_row.source_metadata->>'asset_slot'<>new.source_asset_slot
      or new.source_asset_slot<>new.source_owner_key or asset_row.source_metadata->>'unit_slug'<>unit_slug or new.object_key<>expected_key
    then raise exception using errcode='PZ001',message='release_pin_integrity_failed'; end if;
  else
    expected_key:='builder-native-assets/'||package_slug||'/'||component_slug||'/'||new.source_owner_key||'/assets/'||case when new.asset_role='native_teacher_answer' then 'teacher-answers/' when new.extension in ('mp3','mp4') then new.source_asset_slot||'/' else '' end||new.checksum_sha256||'.'||new.extension;
    if asset_row.source_metadata->>'native_activity_id'<>new.source_owner_key or asset_row.source_metadata->>'asset_slot'<>new.source_asset_slot or new.object_key<>expected_key
    then raise exception using errcode='PZ001',message='release_pin_integrity_failed'; end if;
  end if;
  if new.asset_role='native_teacher_answer' then
    if new.media_type not in ('image/png','image/jpeg','image/webp') or new.extension not in ('png','jpg','webp')
      or not exists (
        select 1 from jsonb_each(release_row.teacher_projection->'nativeActivities') entry,
          lateral jsonb_path_query(entry.value, '$.document.parts[*].solution.**.sampleAnswer.image.reference') ref
        where entry.key=new.source_owner_key and ref->>'assetId'=new.book_asset_id::text
          and ref->>'slot'=new.source_asset_slot and ref->>'checksumSha256'=new.checksum_sha256 and ref->>'role'='native_teacher_answer'
      ) then raise exception using errcode='PZ001',message='release_pin_integrity_failed'; end if;
  end if;
  return new;
end $$;
